function user(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',vb='47C98A957290369BE500498D090B7BFA.cache.html',tb='6869420EFFA9BD60607B173B7F8167CB.cache.html',wb='7A8EB40C791BB4ECDE992A66A6C32F4C.cache.html',cc='<script defer="defer">user.onInjectionDone(\'user\')<\/script>',gc='<script id="',A='=',q='?',C='Bad handler "',ub='CDDCEECE31163E557E3FB8737FDFD1C3.cache.html',sb='D083E5E37DF56ACFA245E4243137A133.cache.html',bc='DOMContentLoaded',Fb='Diagrams.css',ac='DragDrop.css',o='SCRIPT',fc='__gwt_marker_user',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',ec='end',lb='gecko',mb='gecko1_8',Eb='gwt-cal-google.css',yb='gwt.hybrid',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',Db='head',qb='hosted.html?user',Cb='href',kb='ie6',ab='iframe',t='img',bb="javascript:''",zb='link',pb='loadExternalRefs',v='meta',eb='moduleRequested',dc='moduleStartup',jb='msie',w='name',gb='opera',db='position:absolute;width:0;height:0;border:none',Ab='rel',ib='safari',rb='selectingPermutation',xb='starrating/starrating.css',x='startup',Bb='stylesheet',ob='unknown',m='user',fb='user.agent',hb='webkit';var ic=window,k=document,hc=ic.__gwtStatsEvent?function(a){return ic.__gwtStatsEvent(a)}:null,Cc,sc,nc,mc=l,vc={},Fc=[],Bc=[],lc=[],yc,Ac;hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!ic.__gwt_stylesLoaded){ic.__gwt_stylesLoaded={}}if(!ic.__gwt_scriptsLoaded){ic.__gwt_scriptsLoaded={}}function rc(){var b=false;try{b=ic.external&&(ic.external.gwtOnLoad&&ic.location.search.indexOf(yb)==-1)}catch(a){}rc=function(){return b};return b}
function uc(){if(Cc&&sc){var c=k.getElementById(m);var b=c.contentWindow;if(rc()){b.__gwt_getProperty=function(a){return oc(a)}}user=null;b.gwtOnLoad(yc,m,mc);hc&&hc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:ec})}}
function pc(){var j,h=fc,i;k.write(gc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){mc=f(j.src)}if(mc==l){var e=k.getElementsByTagName(s);if(e.length>0){mc=e[e.length-1].href}else{mc=f(k.location.href)}}else if(mc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=mc+u;mc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function zc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}vc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{Ac=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{yc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function Ec(d,e){var a=lc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function oc(d){var e=Bc[d](),b=Fc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Ac){Ac(d,a,e)}throw null}
var qc;function tc(){if(!qc){qc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);hc&&hc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(mc+Dc)}}
Bc[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return kb}}}else if(d.indexOf(lb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return mb}return lb}return ob};Fc[fb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};user.onScriptLoad=function(){if(qc){sc=true;uc()}};user.onInjectionDone=function(){Cc=true;hc&&hc({moduleName:m,subSystem:x,evtGroup:pb,millis:(new Date()).getTime(),type:ec});uc()};pc();var Dc;if(rc()){if(ic.external.initModule&&ic.external.initModule(m)){ic.location.reload();return}Dc=qb}zc();hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:rb});if(!Dc){try{Ec([gb],sb);Ec([mb],tb);Ec([lb],ub);Ec([ib],vb);Ec([kb],wb);Dc=lc[oc(fb)]}catch(a){return}}var xc;function wc(){if(!nc){nc=true;if(!__gwt_stylesLoaded[xb]){var a=k.createElement(zb);__gwt_stylesLoaded[xb]=a;a.setAttribute(Ab,Bb);a.setAttribute(Cb,mc+xb);k.getElementsByTagName(Db)[0].appendChild(a)}if(!__gwt_stylesLoaded[Eb]){var a=k.createElement(zb);__gwt_stylesLoaded[Eb]=a;a.setAttribute(Ab,Bb);a.setAttribute(Cb,mc+Eb);k.getElementsByTagName(Db)[0].appendChild(a)}if(!__gwt_stylesLoaded[Fb]){var a=k.createElement(zb);__gwt_stylesLoaded[Fb]=a;a.setAttribute(Ab,Bb);a.setAttribute(Cb,mc+Fb);k.getElementsByTagName(Db)[0].appendChild(a)}if(!__gwt_stylesLoaded[ac]){var a=k.createElement(zb);__gwt_stylesLoaded[ac]=a;a.setAttribute(Ab,Bb);a.setAttribute(Cb,mc+ac);k.getElementsByTagName(Db)[0].appendChild(a)}uc();if(k.removeEventListener){k.removeEventListener(bc,wc,false)}if(xc){clearInterval(xc)}}}
if(k.addEventListener){k.addEventListener(bc,function(){tc();wc()},false)}var xc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){tc();wc()}},50);hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:ec});hc&&hc({moduleName:m,subSystem:x,evtGroup:pb,millis:(new Date()).getTime(),type:nb});k.write(cc)}
user();